In [1]:
%load_ext autoreload
%autoreload 2

In [52]:
import numpy as np
from pandas import DataFrame
import matplotlib.pyplot as plt
from kirill_korolev_v1 import pa, pb, pc, pd, pc_ab, pc_abd, pc_d, pc_a, pc_b

In [97]:
class Distribution:
    def __init__(self, name, p, values):
        self.name = name
        self.p = p
        self.values = values
    
    def k_moment(self, k):
        values = self.values ** k
        result = np.tensordot(values, self.p, axes=1)
        if len(result.shape) == 0:
            return result.item()
        return result

    def expectation(self):
        return self.k_moment(1)

    def variance(self):
        return self.k_moment(2) - (self.expectation()**2)

In [98]:
params = {'amin': 75, 'amax': 90, 'bmin': 500, 'bmax': 600,
              'p1': 0.1, 'p2': 0.01, 'p3': 0.3}

In [99]:
dists_map = {'pa': pa(params, 1), 'pb': pb(params, 1),
             'pc1': pc(params, 1), 'pc2': pc(params, 2),
             'pd1': pd(params, 1), 'pd2': pd(params, 2)}
expectations = {}
variances = {}

for name, dist_tuple in dists_map.items():
    dist = Distribution(name, *dist_tuple)
    expectations[name] = dist.expectation()
    variances[name] = dist.variance()

In [101]:
stats = DataFrame(index=dists_map.keys(), columns=['expectation', 'variance'])
stats['expectation'] = expectations.values()
stats['variance'] = variances.values()
stats = stats.round(3)

stats

expectation  variance
pa        82.500    21.250
pb       550.000   850.000
pc1       13.750    13.168
pc2       13.750    14.048
pd1       17.875    25.141
pd2       17.875    26.628

In [103]:
pa_dist = Distribution('pa', *dists_map['pa'])
a_exp = round(pa_dist.expectation())

pb_dist = Distribution('pb', *dists_map['pb'])
b_exp = round(pb_dist.expectation())

pd_dist = Distribution('pd1', *dists_map['pd1'])
d_exp = round(pd_dist.expectation())

In [104]:
pc_dist = Distribution('pc', *pc(params, 1))
pc_dist.expectation(), pc_dist.variance()

(13.749999999999995, 13.167500000000075)

In [105]:
pca_dist = Distribution('pc_a', *pc_a(np.array([a_exp]), params, 1))
pca_dist.expectation(), pca_dist.variance()

(array([13.7]), array([12.91]))

In [106]:
pcb_dist = Distribution('pc_b', *pc_b(np.array([b_exp]), params, 1))
pcb_dist.expectation(), pcb_dist.variance()

(array([13.75]), array([13.0825]))

In [107]:
pcd_dist = Distribution('pc_d', *pc_d(np.array([d_exp]), params, 1))
pcd_dist.expectation(), pcd_dist.variance()

(array([13.8959706]), array([1.5335817]))

In [108]:
pcab_dist = Distribution('pc_ab', *pc_ab(np.array([a_exp]), np.array([b_exp]), params, 1))
pcab_dist.expectation(), pcab_dist.variance()

(array([[13.7]]), array([[12.825]]))

In [109]:
pcabd_dist = Distribution('pc_abd', *pc_abd(np.array([a_exp]), np.array([b_exp]), np.array([d_exp]), params, 1))
pcabd_dist.expectation(), pcabd_dist.variance()

(array([[[13.8908725]]]), array([[[1.52942458]]]))